Documentation:
  - head-branch: ["^dev/docs"]
  - changed-files:
      - any-glob-to-any-file: "docs/**"
Frontend:
  - head-branch: ["^dev/frontend"]
  - changed-files:
      - any-glob-to-any-file: ["**.html", "**.css", "**.js"]
Backend:
  - head-branch: ["^dev/backend"]
  - changed-files:
      - any-glob-to-any-file: ["**.py", "**.js", "**.java", "**.php", "**.rb"]
Database:
  - head-branch: ["^dev/database"]
  - changed-files:
      - any-glob-to-any-file: ["**.sql"]
Review:
  - head-branch: ["^dev/review"]
