Documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
Frontend:
  - head-branch: ["dev/frontend"]
  - changed-files:
      - any-glob-to-any-file: ["**.html", "**.css", "**.js"]
Backend:
  - head-branch: ["dev/backend"]
  - changed-files:
      - any-glob-to-any-file: ["**.py"]
Database:
  - changed-files:
      - any-glob-to-any-file: ["**.sql"]
