-- MySQL Script generated by MySQL Workbench
-- Mon Jul  8 16:07:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema walmartdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema walmartdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `walmartdb` DEFAULT CHARACTER SET utf8 ;
USE `walmartdb` ;

-- -----------------------------------------------------
-- Table `walmartdb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walmartdb`.`Employee` (
  `Employee_id` INT NOT NULL,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Start_date` DATETIME NULL,
  `Position` VARCHAR(45) NULL,
  `Hourly_wage` DECIMAL NULL,
  `Salary` DECIMAL NULL,
  PRIMARY KEY (`Employee_id`),
  UNIQUE INDEX `Ssn_UNIQUE` (`Employee_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walmartdb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walmartdb`.`Transaction` (
  `Transaction_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Employee_id` INT NOT NULL,
  `Item_id` INT NOT NULL,
  `Item_price` DECIMAL NULL,
  `Purchase_date` DATETIME NULL,
  `Return_date` DATETIME NULL,
  PRIMARY KEY (`Transaction_id`, `Customer_id`, `Employee_id`, `Item_id`),
  UNIQUE INDEX `Transaction_id_UNIQUE` (`Transaction_id` ASC) VISIBLE,
  UNIQUE INDEX `Customer_id_UNIQUE` (`Customer_id` ASC) VISIBLE,
  UNIQUE INDEX `Employee_id_UNIQUE` (`Employee_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walmartdb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walmartdb`.`Customer` (
  `Customer_id` INT NOT NULL,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_id`),
  UNIQUE INDEX `Customer_id_UNIQUE` (`Customer_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walmartdb`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walmartdb`.`Vendor` (
  `Vendor` INT NOT NULL,
  PRIMARY KEY (`Vendor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
